[[headers]]
  for = "/*"  # Aplica la protecci칩n a todo el sitio
  [headers.values]
    Authorization = "Basic dXN1YXJpbzpjbGF2ZQ=="  # Autenticaci칩n b치sica con usuario "clave" y contrase침a "clave"
